from __future__ import annotations

from typing import Dict, Optional, Tuple

# ── Dotenv prefix mappings (for .env/.env.example scanning) ──────────
# Maps env var prefixes → (category, framework_name)

_DOTENV_PREFIXES: Dict[str, Tuple[str, str]] = {
    "SENTRY_": ("infra", "sentry"),
    "STRIPE_": ("saas", "stripe"),
    "OTEL_": ("infra", "opentelemetry"),
    "GOOGLE_": ("infra", "gcp"),
    "AWS_": ("infra", "aws"),
    "DATABASE_URL": ("database", "postgresql"),
    "REDIS_URL": ("database", "redis"),
    "NEXT_PUBLIC_": ("frontend", "nextjs"),
    "MEDUSA_": ("backend", "medusa"),
    "NODE_ENV": ("language", "node"),
    "OPENAI_API_KEY": ("saas", "openai"),
    "ANTHROPIC_API_KEY": ("saas", "anthropic"),
    "SLACK_": ("saas", "slack"),
    "TWILIO_": ("saas", "twilio"),
    "SENDGRID_": ("saas", "sendgrid"),
    "DATABASE_HOST": ("database", "postgresql"),
    "DATABASE_NAME": ("database", "postgresql"),
    "DATABASE_USER": ("database", "postgresql"),
    "DATABASE_PASSWORD": ("database", "postgresql"),
}

# ── Docker image name mappings (for docker-compose.yml / Dockerfile / compose.yaml) ─

_DOCKER_IMAGE_MAP: Dict[str, Tuple[str, str]] = {
    "postgres": ("database", "postgresql"),
    "redis": ("database", "redis"),
    "nginx": ("infra", "nginx"),
    "node": ("language", "node"),
    "python": ("language", "python"),
    "golang": ("language", "go"),
    "rust": ("language", "rust"),
    "mariadb": ("database", "mariadb"),
    "mysql": ("database", "mysql"),
    "mongo": ("database", "mongodb"),
    "elasticsearch": ("database", "elasticsearch"),
    "rabbitmq": ("backend", "rabbitmq"),
    "traefik": ("infra", "traefik"),
    "caddy": ("infra", "caddy"),
    "prom": ("infra", "prometheus"),
    "grafana": ("infra", "grafana"),
    "alpine": ("other", "alpine"),
    "ubuntu": ("other", "ubuntu"),
}

# Top npm packages with categories
_TOP_NPM: Dict[str, str] = {
    "react": "frontend",
    "next": "frontend",
    "vue": "frontend",
    "svelte": "frontend",
    "angular": "frontend",
    "express": "backend",
    "@nestjs/core": "backend",
    "@nestjs/common": "backend",
    "@nestjs/platform-express": "backend",
    "fastify": "backend",
    "hono": "backend",
    "socket.io": "backend",
    "passport": "backend",
    "typeorm": "database",
    "prisma": "database",
    "mongoose": "database",
    "sequelize": "database",
    "knex": "database",
    "drizzle-orm": "database",
    "pg": "database",
    "ioredis": "database",
    "redis": "database",
    "mysql2": "database",
    "mongodb": "database",
    "typescript": "language",
    "eslint": "tooling",
    "prettier": "tooling",
    "jest": "testing",
    "vitest": "testing",
    "mocha": "testing",
    "cypress": "testing",
    "playwright": "testing",
    "@playwright/test": "testing",
    "chai": "testing",
    "supertest": "testing",
    "axios": "other",
    "lodash": "other",
    "moment": "other",
    "date-fns": "other",
    "zod": "other",
    "yup": "other",
    "uuid": "other",
    "dotenv": "other",
    "cors": "backend",
    "helmet": "backend",
    "graphql": "backend",
    "apollo-server": "backend",
    "@apollo/client": "frontend",
    "next-auth": "backend",
    "next-intl": "frontend",
    "react-dom": "frontend",
    "react-router-dom": "frontend",
    "react-hook-form": "frontend",
    "@reduxjs/toolkit": "frontend",
    "redux": "frontend",
    "zustand": "frontend",
    "tailwindcss": "ui_library",
    "shadcn-ui": "ui_library",
    "styled-components": "ui_library",
    "@emotion/react": "ui_library",
    "framer-motion": "ui_library",
    "@radix-ui/react-dialog": "ui_library",
    "@radix-ui/react-dropdown-menu": "ui_library",
    "@radix-ui/react-popover": "ui_library",
    "lucide-react": "ui_library",
    "recharts": "ui_library",
    "chart.js": "ui_library",
    "d3": "ui_library",
    "swiper": "ui_library",
    "webpack": "tooling",
    "vite": "frontend",
    "turbo": "tooling",
    "nx": "tooling",
    "babel": "tooling",
    "postcss": "tooling",
    "autoprefixer": "tooling",
    "sass": "tooling",
    "less": "tooling",
    "esbuild": "tooling",
    "rollup": "tooling",
    "nodemon": "tooling",
    "husky": "tooling",
    "lint-staged": "tooling",
    "commitlint": "tooling",
}

# Top Python packages with categories
_TOP_PYPI: Dict[str, str] = {
    "django": "backend",
    "flask": "backend",
    "fastapi": "backend",
    "aiohttp": "backend",
    "starlette": "backend",
    "uvicorn": "backend",
    "gunicorn": "backend",
    "celery": "backend",
    "pydantic": "backend",
    "click": "other",
    "numpy": "other",
    "pandas": "other",
    "matplotlib": "other",
    "scipy": "other",
    "scikit-learn": "other",
    "tensorflow": "other",
    "torch": "other",
    "transformers": "other",
    "pillow": "other",
    "requests": "other",
    "httpx": "other",
    "aiofiles": "other",
    "jinja2": "other",
    "psycopg2": "database",
    "psycopg2-binary": "database",
    "sqlalchemy": "database",
    "alembic": "database",
    "asyncpg": "database",
    "redis": "database",
    "pymongo": "database",
    "djongo": "database",
    "pytest": "testing",
    "pytest-cov": "testing",
    "pytest-asyncio": "testing",
    "black": "tooling",
    "ruff": "tooling",
    "mypy": "tooling",
    "isort": "tooling",
    "flake8": "tooling",
    "pre-commit": "tooling",
    "poetry": "tooling",
    "pip-tools": "tooling",
    "boto3": "other",
    "motor": "database",
    "redis-py": "database",
    "django-storages": "backend",
    "django-cors-headers": "backend",
    "django-rest-framework": "backend",
    "djangorestframework": "backend",
    "graphene": "backend",
    "strawberry-graphql": "backend",
    "sanic": "backend",
    "tornado": "backend",
    "uvloop": "other",
    "watchfiles": "tooling",
}

# Top Go packages with categories
_TOP_GO: Dict[str, str] = {
    "github.com/gin-gonic/gin": "backend",
    "github.com/labstack/echo": "backend",
    "github.com/gorilla/mux": "backend",
    "github.com/gofiber/fiber": "backend",
    "github.com/chi-go/chi": "backend",
    "github.com/go-chi/chi": "backend",
    "github.com/valyala/fasthttp": "backend",
    "github.com/grpc/grpc-go": "backend",
    "google.golang.org/grpc": "backend",
    "github.com/golang-jwt/jwt": "backend",
    "github.com/golang-jwt/jwt/v5": "backend",
    "github.com/jackc/pgx": "database",
    "github.com/jackc/pgx/v5": "database",
    "github.com/lib/pq": "database",
    "github.com/go-sql-driver/mysql": "database",
    "github.com/mattn/go-sqlite3": "database",
    "gorm.io/gorm": "database",
    "gorm.io/driver/postgres": "database",
    "gorm.io/driver/mysql": "database",
    "github.com/jmoiron/sqlx": "database",
    "github.com/redis/go-redis": "database",
    "github.com/go-redis/redis": "database",
    "github.com/mongodb/mongo-go-driver": "database",
    "go.mongodb.org/mongo-driver": "database",
    "github.com/stretchr/testify": "testing",
    "github.com/stretchr/testify/assert": "testing",
    "testing": "testing",
    "github.com/golang/mock": "testing",
    "github.com/onsi/ginkgo": "testing",
    "github.com/onsi/gomega": "testing",
    "github.com/cucumber/godog": "testing",
    "github.com/prometheus/client_golang": "other",
    "github.com/spf13/cobra": "other",
    "github.com/spf13/viper": "other",
    "github.com/urfave/cli": "other",
    "github.com/rs/zerolog": "other",
    "go.uber.org/zap": "other",
    "github.com/sirupsen/logrus": "other",
    "github.com/graphql-go/graphql": "backend",
    "github.com/99designs/gqlgen": "backend",
    "github.com/hashicorp/terraform": "infra",
    "github.com/aws/aws-sdk-go": "other",
    "github.com/aws/aws-sdk-go-v2": "other",
    "google.golang.org/api": "other",
    "github.com/gorilla/websocket": "backend",
    "github.com/nats-io/nats.go": "backend",
    "github.com/segmentio/kafka-go": "backend",
    "github.com/confluentinc/confluent-kafka-go": "backend",
}

# Top Cargo crates with categories
_TOP_CARGO: Dict[str, str] = {
    "tokio": "backend",
    "actix-web": "backend",
    "axum": "backend",
    "warp": "backend",
    "rocket": "backend",
    "hyper": "backend",
    "reqwest": "other",
    "serde": "other",
    "serde_json": "other",
    "thiserror": "other",
    "anyhow": "other",
    "clap": "other",
    "tracing": "other",
    "log": "other",
    "chrono": "other",
    "regex": "other",
    "rand": "other",
    "uuid": "other",
    "sqlx": "database",
    "diesel": "database",
    "sea-orm": "database",
    "mongodb": "database",
    "redis": "database",
    "rusqlite": "database",
    "tower": "backend",
    "tower-http": "backend",
    "tonic": "backend",
    "prost": "other",
    "lazy_static": "other",
    "once_cell": "other",
    "itertools": "other",
    "futures": "other",
    "async-trait": "other",
    "tokio-postgres": "database",
    "deadpool-postgres": "database",
    "bb8": "database",
    "rusoto_core": "other",
    "image": "other",
    "csv": "other",
    "rayon": "other",
    "enum_dispatch": "other",
    "strum": "other",
    "derive_more": "other",
}

# Known prefixes for npm packages (kategorisiert)
_KNOWN_PREFIXES: Dict[str, str] = {
    "@medusajs/": "backend",
    "@radix-ui/": "ui_library",
    "@radix-ui/react-": "ui_library",
    "react-": "frontend",
    "@next": "frontend",
    "eslint-": "tooling",
    "@types/": "tooling",
    "@testing-library/": "testing",
    "@storybook/": "tooling",
    "@emotion/": "ui_library",
    "@mantine/": "ui_library",
    "@chakra-ui/": "ui_library",
    "@mui/": "ui_library",
    "@material-ui/": "ui_library",
    "@ant-design/": "ui_library",
    "@nestjs/": "backend",
    "@aws-sdk/": "other",
    "@aws-cdk/": "infra",
    "@typescript-eslint/": "tooling",
    "@trpc/": "backend",
    "@tanstack/": "frontend",
    "@vue/": "frontend",
    "@sveltejs/": "frontend",
    "@angular/": "frontend",
    "@capacitor/": "frontend",
    "@expo/": "frontend",
    "@react-": "frontend",
    "@fontsource/": "ui_library",
    "@hookform/": "frontend",
    "@icons/": "ui_library",
    "@internationalized/": "other",
    "@langchain/": "other",
    "@opentelemetry/": "other",
    "@planetscale/": "database",
    "@prisma/": "database",
    "@pulumi/": "infra",
    "@reduxjs/": "frontend",
    "@sentry/": "other",
    "@shopify/": "backend",
    "@supabase/": "backend",
    "@tailwindcss/": "ui_library",
    "@vercel/": "frontend",
    "django-": "backend",
    "python-": "other",
    "flask-": "backend",
    "fastapi-": "backend",
    "google-": "other",
    "pytest-": "testing",
}

# Prefixes für Go Modules
_GO_PREFIXES: Dict[str, str] = {
    "github.com/gin-gonic/": "backend",
    "github.com/labstack/": "backend",
    "github.com/gofiber/": "backend",
    "github.com/gorilla/": "backend",
    "github.com/go-chi/": "backend",
    "github.com/jackc/": "database",
    "github.com/lib/": "database",
    "github.com/go-sql-driver/": "database",
    "github.com/mattn/": "other",
    "gorm.io/": "database",
    "github.com/redis/": "database",
    "github.com/mongodb/": "database",
    "go.mongodb.org/": "database",
    "github.com/stretchr/": "testing",
    "github.com/golang/": "testing",
    "github.com/onsi/": "testing",
    "github.com/cucumber/": "testing",
    "github.com/prometheus/": "other",
    "github.com/spf13/": "other",
    "github.com/urfave/": "other",
    "github.com/rs/": "other",
    "go.uber.org/": "other",
    "github.com/sirupsen/": "other",
    "github.com/hashicorp/": "infra",
    "github.com/aws/": "other",
    "google.golang.org/": "other",
    "github.com/nats-io/": "backend",
    "github.com/segmentio/": "backend",
    "github.com/confluentinc/": "backend",
    "github.com/graphql-go/": "backend",
    "github.com/99designs/": "backend",
    "github.com/grpc/": "backend",
}

# Category-Lookup helper — merged dict für schnelle Suche


def _lookup_category(name: str, known: Dict[str, str],
                     prefixes: Dict[str, str]) -> Optional[str]:
    """Sucht nach bekanntem Namen, dann nach Prefix."""
    # 1. Exakter Match
    cat = known.get(name)
    if cat:
        return cat
    # 2. Prefix-Match
    for prefix, category in prefixes.items():
        if name.startswith(prefix):
            return category
    return None
